name: Sync README to Issue

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:     # 支持手动触发

jobs:
  sync-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch README content
      id: fetch-readme
      run: |
        # 使用原始GitHub URL获取内容
        CONTENT=$(curl -sL "https://raw.githubusercontent.com/russianqin/WenZhangShouCang/main/README.md")
        
        # 对内容进行JSON转义
        JSON_CONTENT=$(echo -n "$CONTENT" | jq -Rs .)
        
        # 保存到文件供后续步骤使用
        echo "$JSON_CONTENT" > content.json
        
        # 设置输出变量
        echo "content_file=content.json" >> $GITHUB_OUTPUT
      
      # 确保安装了jq工具
      # 如果基础镜像没有jq，可以添加安装步骤：sudo apt-get install -y jq

    - name: Update Issue
      uses: actions/github-script@v6
      with:
        script: |
          // 读取之前保存的内容文件
          const fs = require('fs');
          const content = JSON.parse(fs.readFileSync('${{ steps.fetch-readme.outputs.content_file }}', 'utf8'));
          
          // 更新issue
          await github.rest.issues.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: 20,
            body: content
          });
          
          console.log('Issue #20 updated successfully');
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
